### ISSUE TITLE
Add support for a "limit" parameter

### ISSUE THREAD

**Issue by thadguidry** [wetneb/openrefine-wikidata#1]
OpenRefine and the old Freebase Reconcile service supported a "limit" parameter.
In the Reconcile column dialog this is called "Maximum number of candidates to return".
Code is here: https://github.com/OpenRefine/OpenRefine/blob/d5fb07384242d07241b0ce103c47d930046f1135/main/src/com/google/refine/model/recon/StandardReconConfig.java#L170
Screenshot here: https://github.com/OpenRefine/OpenRefine/issues/805#issuecomment-228560259

Thanks so much for beginning work on this !

**Comment by wetneb** [comment]
@thadguidry sure, that should not be hard…
