### ISSUE TITLE
Support querying additional columns "As Property" to increase match score

### ISSUE THREAD

**Issue by thadguidry** [wetneb/openrefine-wikidata#2]
The old Freebase Reconcile accepted a parameter called "columnDetails" to help pass additional columns to the Reconcile service to help increase match scoring.

Some Code: https://github.com/OpenRefine/OpenRefine/blob/d5fb07384242d07241b0ce103c47d930046f1135/main/src/com/google/refine/model/recon/StandardReconConfig.java#L212

Here is a simple test case CSV that can be added to test functionality once implemented:

Title,Published In,Author
"Ovarian Cancer",International Journal of Medical Sciences,E VisonÃ 
"Trilobita Walch, 1771",,		
Insecticide,JAMA,Steketee

Matches:
https://www.wikidata.org/wiki/Q24791449
https://www.wikidata.org/wiki/Q21032691
https://www.wikidata.org/wiki/Q21032524

**Comment by wetneb** [comment]
@thadguidry this is alreay partly implemented: the service expects a wikidata property (such as P856) as property name. But I'm not happy with the scoring for now. Ideally users should be able to specify a matching method that suits their data.

**Comment by thadguidry** [comment]
You mean like this ?
![capture](https://cloud.githubusercontent.com/assets/986438/22627022/a0d10eb8-eb7f-11e6-98d8-79884673c973.PNG)

**Comment by wetneb** [comment]
exactly!

**Comment by thadguidry** [comment]
Freebase had a suggest service that would populate those boxes and give a multi-choice for the user to pick from potential properties that are applicable for the choosen Type. (I think some of that code is now removed from OpenRefine 2.6 Beta...maybe not all the way...

Your missing that separate "suggest" service as well then :) for property suggestions.
Ah, here's some of our code for looking at that "suggest" service for property hints is here:
https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js#L240

But I think there is already something similar that powers Wikidata dropdowns for properties ?
![capture](https://cloud.githubusercontent.com/assets/986438/22627145/c3c34b68-eb82-11e6-964e-580ae39ca0fd.PNG)

**Comment by wetneb** [comment]
Right, that makes more sense than bare property ids. I do intend to wrap the WIkidata autocompletion into a "suggest" service.

**Comment by thadguidry** [comment]
Awesome...as for as the OpenRefine impacts... you might have to leverage other OpenRefine developers like https://github.com/jackyq2015 whom I think is the one who initally removed some of the Freebase code from OpenRefine.  Check with him on those details, etc.

**Comment by thadguidry** [comment]
Additionally, looks like you might want to support "properties for this type"
https://www.wikidata.org/wiki/Property:P1963

I wonder if the existing property drop down hinter for Wikipedia even uses some of that data ??

**Comment by wetneb** [comment]
Given the current specification for the API it seems to me that we don't have access to the target type when proposing properties, so it would be hard to take P1963 into account. But maybe that's a change worth integrating in the API.

I've added the suggest APIs to the endpoint.

**Comment by wetneb** [comment]
@thadguidry About your test dataset, I don't think my interface will ever be able to work for it. No matter how good my re-ranking is, the Wikidata search interface only returns 50 results per query so the target items will not be included in the results. If we can convince the admins to give us a bot account for that, it might go up to 500 results per query, but even in that case, your example with "ovarian cancer" is a long shot.

There could be the option of adding some values of the target properties in the search string, but that seems dangerous in general (it might work for specific examples but impair the results in other cases).

Anyway I have another test dataset to show you:

city,country
Cambridge,US
Cambridge,GB
Paris,FR
Paris,US

The second column is the country code for the country that contains the city. So, we need to traverse two statements to get this value from an item representing a city. The interface does support that, although with a slightly convoluted syntax (inspired by SPARQL):
![selection](https://cloud.githubusercontent.com/assets/309908/22717658/4836cb64-ed94-11e6-8969-a1dac1dd4794.png)

You get matching results that are strictly better than using name-only search:
![dataset](https://cloud.githubusercontent.com/assets/309908/22717676/61f6ef84-ed94-11e6-94f2-89837aa13be8.png)

I hope this validates the feature!

**Comment by thadguidry** [comment]
Yes it works... looks like we need to improve the fuzzy matching algorithm to give something like a 25% scoring increase for matching property columns ?

The highlighted topic should have scored above 90 since the Video Game columns has a matching contains word...and the Publisher column is exact matching.

![capture](https://cloud.githubusercontent.com/assets/986438/22743254/4d544f22-eddf-11e6-8b39-bdab4281d54d.PNG)

**Comment by wetneb** [comment]
Yeah the weights that I have picked are completely arbitrary, so I am happy to change them… Currently the score is the weighted average of the matching score of title and properties, where title has weight 1 and properties have weight 0.4.

In your case the matching score for the title is very low, because "Journey" only matches a small part of "Fable: The Journey". That's also something worth tuning (picking other fuzzy-matchers).
Also, I think it would be interesting to adapt the fuzzy-matcher depending on the type of the data (quantity / identifier / human language).

I will try to find some time to look more carefully for some literature on the topic but I have little hopes to find anything useful as the case we are looking at is very generic.

**Comment by thadguidry** [comment]
@wetneb don't bother with literature for this stuff. :)  We found with Freebase Reconcile that just applying real usecases and tweaks got us really close to perfection.  We came to the conclusion that Properties are much more important especially when filled in and matching.

In Freebase we called them Disambiguating Properties... you actually HAVE that data in the Freebase Dumps :) but doubtful that anyone at WD knows how much gold they are sitting on with the Freebase data. With that data a bot could automatically fill in the P1963 for lots of Classes (Types).  Anyways, I digress.

Perhaps having a simple 1st pass algorithm to give Dynamic Weighting for Properties in the query.
For instance... Video Game  https://www.wikidata.org/wiki/Q7889

Using P1963 "properties for this type" you can get a hint of the most important properties for that Video Game Class or Type...those important Disambiguating Properties.  Perhaps give them a weight of .75 and any others you can give .4
