### ISSUE TITLE
Search preview

### ISSUE THREAD

**Issue by ettorerizza** [wetneb/openrefine-wikidata#20]
After a reconciliation, when no candidate is suitable, it's sometimes necessary to modify the spelling of the term by using the "search" function. 

But Wikidata then returns so many homonyms, and Qids bring so little information, that it is difficult to choose the right one without previewing each Wikidata page returned. 

![sans titre 2](https://user-images.githubusercontent.com/6286410/28684589-3a2c49ee-7305-11e7-9c5e-c48364859587.jpg)

There was a system of this type with Freebase or with the OpenCorporates reconciliation service. 

![sans titre 1](https://user-images.githubusercontent.com/6286410/28684620-4fb03e74-7305-11e7-9334-80dbd06e637c.jpg)

It would be a great improvement if it could be implemented easily. :)

Thanks again for this very useful service!

PS: I'm sure the point had to be touched elsewhere, but I did not find it.

**Comment by wetneb** [comment]
@ettorerizza yes I think that is what OpenRefine calls the "flyout" service… I had no clue what it was when I implement the interface so I did not do it. It just isn't documented anywhere as far as I can tell. I definitely agree we need it!
