### ISSUE TITLE
Error 500 returned for some (in)valid requests

### ISSUE THREAD

**Issue by Tpt** [wetneb/openrefine-wikidata#21]
These requests are rising a error 500, they should work or return a error 4XY
* https://tools.wmflabs.org/openrefine-wikidata/en/api?query={'query':'foo'} (invalid JSON serialisation)
* https://tools.wmflabs.org/openrefine-wikidata/en/api?query=foo (valid request according to the documentation)

**Comment by wetneb** [comment]
@Tpt oh I didn't get that `query=foo` was valid… that's quite ugly to allow free-form text and JSON in the same field :-/
