### ISSUE TITLE
Incomplete results for the reconciliation of "George Washington"

### ISSUE THREAD

**Issue by Tpt** [wetneb/openrefine-wikidata#22]
The query http://tools.wmflabs.org/openrefine-wikidata/en/api?query={%22query%22:%22George+Washington%22,%22limit%22:1000} (reconciliation of "George Washington") returns less results than it should. It would be expected that [George Washington (Q1508517)](https://www.wikidata.org/wiki/Q1508517) would be in the results but it is not.

**Comment by ettorerizza** [comment]
@Tpt My question is a bit off topic, but how would you use this syntax to search for "George Washington" only if they are an instance of "Human" (Q5)?

**Comment by Tpt** [comment]
@ettorerizza http://tools.wmflabs.org/openrefine-wikidata/en/api?query={"query":"George+Washington","limit":1000,"type":"Q5"} The documentation of the API is here: https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation-Service-API

**Comment by ettorerizza** [comment]
Arf, it was under my eyes... I thought that this part of the documentation was related to Freebase and now outdated. thank you !

**Comment by wetneb** [comment]
The interface fetches at most 50 candidates from both wbsearchentities and the mediawiki search (so, the autocompletion and the search page in the UI). So it will not retrieve more than 100 candidates. We could page for more matches but it would make the interface even slower.

Ideally I'd like to use a dedicated search engine for the reconciliation interface.
Search accuracy on Wikidata is notoriously bad but WMDE is working on it so I will wait for them to complete their enhancements before deciding to move to a custom solution.

**Comment by wetneb** [comment]
This will be fixed when WMDE deploys their new search engine, which can be tried at http://wikidata-wdsearch.wmflabs.org/wiki/Special:Search
As this is outside my control, I am closing this
