### ISSUE TITLE
Autocomplete: show main label instead of matched alias

### ISSUE THREAD

**Issue by wetneb** [wetneb/openrefine-wikidata#25]
When searching for "start date", two properties show up with apparently the same name, whereas one has that as label and the other as alias. The behaviour of the autocomplete endpoint should match that of Wikidata.

**Comment by thadguidry** [comment]
Hmm... In Freebase we had the flexibility to do both.  In fact, if you search our old mailing lists, I specifically was the one who asked Andy to put in an "alias" parameter to have the Freebase endpoint return both, and were disambiguation came into play was the snippet of the description in the Freebase Suggest flyouts.

I would love for it to work eventually as Freebase did, and autocomplete on both alias or label...but showing extra info from an autocomplete form/window/dropdown that can provide further disambiguation when things have the same name.

Posterity:
```
On Wed, 14 Nov 2012, Thad Guidry wrote:

> I have no idea of language.

That's not true, you know your query was italian.

> I need a wildcard solution.

There are two hacky solutions you can use:

  - slow: use lang=a,b,c,.... all the codes you want
    the more codes you use, the noisier the matches and the slower and bigger
    the query

  - use lang=s/all and prefixed=true
    The lang=s/all hackery is a "let's pretend everything is english" kind of
    thing, all text is indexed as english regardless of language. It only
    works with prefixed=true and only searches on names and aliases.
    While it's much faster then the other solution, it's also very noisy.

Your query appears to work well with the s/all hack but your mileage may 
vary widely:
https://www.googleapis.com/freebase/v1/search?filter=%28all%20name:%22Politecnico%20Torino%22%29&lang=s/all&prefixed=true&indent=true

Andi..

```
