### ISSUE TITLE
Sort the candidates by inverse QID magnitude ?

### ISSUE THREAD

**Issue by ettorerizza** [wetneb/openrefine-wikidata#26]
Hi @wetneb. I come back with my scoring problems. :p

I was wondering: is it technically possible to rank the candidates of a reconciliation in descending order of their QID number ? Let me explain. If I reconcile for example the string "Amsterdam" with a vague category like "Geographic region" (Q82794), the result is often surprising. The first Amsterdam that is proposed is an obscure town of Texas, while the famous city in the Netherlands is only in 4th position. 

![sans titre 1](https://user-images.githubusercontent.com/6286410/32154784-4c4d14be-bd33-11e7-8ead-5d821972280c.jpg)

It's therefore impossible to perform a "match each cell with its best candidate". On the other hand, when you click on "search for match", the right Amsterdam appears directly in first position. 
![sans titre 2](https://user-images.githubusercontent.com/6286410/32154791-5b64eb98-bd33-11e7-99d3-01204c5c2b11.jpg)

It's immediately recognized by the fact that its QID contains only three digits, a sign undoubtedly that it's an important entity created very early in the history of Wikidata, and certainly well before the locality of Texas (Q4748816 ).

If it were possible to perform this ranking, the manual reconciliation task would be greatly facilitated.

**Comment by wetneb** [comment]
It would be totally sensible to do this tie-break for candidates that have the same reconciliation score.
