### ISSUE TITLE
Exclude certain types during reconciliation?

### ISSUE THREAD

**Issue by aprovo** [wetneb/openrefine-wikidata#31]
Currently in OpenRefine there's an option to reconcile against particular types or no particular type; would it be possible to _exclude_ certain types (for example, Wikidata disambiguation pages) during reconciliation? I'm not sure if this is a request better put to the OpenRefine repo; please let me know if so. Thanks!

**Comment by wetneb** [comment]
@aprovo Here is what the reconciliation interface currently does:
* if you do not select any type, it will accept anything that is not some "Wikimedia internal stuff" (https://www.wikidata.org/wiki/Q17442446). If the ontology is not broken, this should get rid of disambiguation pages.
* if you do select a type, then it will accept anything that is of some subclass of this type, including the items that also happen to be marked as Wikimedia internal stuff (items can have multiple types).

In my experience this works reasonably well, but I agree that sometimes it would be nice to be able to exclude custom types too (for instance, match against organizations but exclude football clubs). But that would require a change in the reconciliation API (so, that's on the OpenRefine repo). It's not clear to me what it would look like, but it's surely worth being discussed.

**Comment by aprovo** [comment]
Hmm, I think then something must be broken. When I recently reconciled a column of names against no type, I got a bunch of disambiguation pages (faceted by best candidate's types and had a bunch with type Q4167410).

**Comment by wetneb** [comment]
@aprovo Indeed, I just checked and the ontology was missing a subclass link that I have added back. This should solve the issue.

**Comment by aprovo** [comment]
Thank you!
