### ISSUE TITLE
Is the data extension supposed to work with Wikidata reconciliation in OpenRefine v 3 beta?

### ISSUE THREAD

**Issue by susannaanas** [wetneb/openrefine-wikidata#36]
For me it does not.

I have tried the service in Finnish and in English. Am I missing some settings?

![screen shot 2018-06-16 at 9 39 36](https://user-images.githubusercontent.com/4725416/41496452-76a5d0a0-7149-11e8-8a62-6b2f296746ec.png)

**Comment by wetneb** [comment]
That is surprising. Have you removed the services and added them back?

**Comment by susannaanas** [comment]
That's a pity. I must say that the Wikidata upload is GREAT, but my workflows stumble on other glitches.

**Comment by wetneb** [comment]
you can always fetch them directly with the MediaWiki API, using the add column by fetching URLs operation. Just use this expression:

"https://www.wikidata.org/w/api.php?action=wbgetentities&format=json&props=descriptions&languages=en|fi&ids="+cell.recon.match.id

**Comment by susannaanas** [comment]
Thanks a lot! Running the call and waiting to see what happens. That saved me a lot of time, I was about to investigate that too. It is pretty slow, though. I generally use Google sheets extension for this kind of things but today it stopped working for me.

**Comment by wetneb** [comment]
You can tweak the time between consecutive requests when you start the operation (the default 5000ms is clearly too high for this sort of queries).

**Comment by wetneb** [comment]
If you struggle with parsing, I have just added support for labels, descriptions and aliases: just use "Lfi" for Finnish labels, "Den" for English description, "Ade" for German aliases.

**Comment by susannaanas** [comment]
Wow!! I will check it out soon!
