### ISSUE TITLE
How to create reconciliation data from existing QID's?

### ISSUE THREAD

**Issue by susannaanas** [wetneb/openrefine-wikidata#39]
If I wanted to use the update and add features and had obtained Wikidata QID's with other means than reconciling with OpenRefine, how should I construct the reconciliation data to be able to proceed?

I can reconcile afresh using textual data or the QID's, but that seems unnecessary.

**Comment by wetneb** [comment]
That is currently the only way to proceed. This checks that the qids exist, fetches their names and types. Note that reconciling Qids is significantly faster than reconciling free text - the interface is optimized for this case.

Blindly considering a column as reconciled could potentially be allowed in OpenRefine: https://github.com/OpenRefine/OpenRefine/issues/1596

In any case this will not incur any changes to the reconciliation service, so closing this issue

**Comment by susannaanas** [comment]
Thanks for the answer! (I hope it does not open the issue)
