### ISSUE TITLE
Open Refine extension to accept Wikidata SPARQL queries as input

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wetneb/openrefine-wikidata#7]
The results of SPARQL queries via the Wikidata Query Service can be exported in a number of formats that are accepted input formats in Open Refine. What about writing an Open Refine extension to act as a bridge?

**Comment by wetneb** [comment]
I think LODrefine (a fork of OpenRefine, https://github.com/sparkica/LODRefine) has already got SPARQL features (for instance a SPARQL-based reconciliation service which, if you don't need any fuzzy matching, is the way to go).

But yeah, it would be really nice to be able to create a project based on a SPARQL query!

**Comment by Daniel-Mietchen** [comment]
That sounds interesting. Thanks for the pointer.

**Comment by wetneb** [comment]
The project looks a bit dead though… :-/

**Comment by thadguidry** [comment]
@Daniel-Mietchen Can you code ?  Most of LODRefine was just extension based and those extensions could be tweaked and added to OpenRefine 2.7 RC 1 by a competent Java developer.

**Comment by wetneb** [comment]
Closing this here as it is tracked in https://github.com/OpenRefine/OpenRefine/issues/1212 (this is a client-side issue).
