### ISSUE TITLE
Check out wikidata_suggest

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wetneb/openrefine-wikidata#8]
It seems to be doing something very similar, by different means.

Code: https://github.com/edsu/wikidata_suggest .

Intro post: https://inkdroid.org/2015/05/20/skos-and-wikidata/

**Comment by wetneb** [comment]
Yeah, it uses the same APIs under the hood. The OpenRefine interface has a few additional features though:
 * filtering by type
 * refining using additional columns matched on other properties
 * more careful matching (for instance, if you search for the city named "Cambridge", no auto-match will be done as there are many different "Cambridge" cities). But if you search for "Cambridge" with "GB" as country code, you will get a match.

I guess it would be useful to advertise it as a standalone API, that can be used outside OpenRefine.

**Comment by wetneb** [comment]
We now have far more features than wikidata_suggest! Closing.
