### ISSUE TITLE
Wrong language title displayed

### ISSUE THREAD

**Issue by johtso** [wetneb/openrefine-wikidata#9]
Firstly thank you so much for making this, it was so desperately needed!

I just came across a small issue. I was doing a reconciliation, and one of the suggestions appeared in Macedonian, instead of English. I don't see any reason why that would happen..

https://www.wikidata.org/wiki/Q949879

![image](https://cloud.githubusercontent.com/assets/830800/22975648/63906fc8-f37f-11e6-8abf-2cf339db067e.png)

**Comment by wetneb** [comment]
Thanks for that! It is a curious bug. I have restarted the interface and the bug disappeared… Let me know if you see it again!
